version: '2'
services:
    db:
      image: mariadb
      environment:
                - MYSQL_DATABASE=openbibo
                - MYSQL_USER=test
                - MYSQL_PASSWORD=test
                - MYSQL_ROOT_PASSWORD=root
      ports:
            - "3306:3306"
    phpmyadmin:
     image: phpmyadmin/phpmyadmin
     environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: root
     ports:
            - "8080:80"
     links:
            - "db:db"
